### PR TITLE
Include package directory path for nuget restore

### PR DESCRIPTION
**Pull request by jitinjohn**
Simple fix for build

### CODE REVIEW

**Comment by davidebbo** [comment]
I just tried running `BuildPackage.cmd` on a clean repo and it worked fine. Are you getting an error?

**Comment by jitinjohn** [comment]
In my case, the packages folder was not created.

It depends on how your global nuget configuration are. Better fix is to
have a local nuget.config in repo root with package directory setting.

Regards,
Jitin John

**Comment by davidebbo** [comment]
Sounds good, thanks for the contrib!

**Comment by jitinjohn** [comment]
Thanks.

Regards,
Jitin John

**Pull request merged**
