### PR TITLE
Added Scoop bucket

### PR DESCRIPTION
**Pull request by snobu**
Added https://scoop.sh bucket -- https://github.com/lukesampson/scoop/pull/2588/commits/807e2b0a9355a6c710b5caf501ad4daced02869a

### CODE REVIEW

**Comment by snobu** [comment]
Should i add `AADClient.exe` to the list of binaries or is that not really supposed to be invoked on its own?

**Comment by davidebbo** [comment]
Never heard of scoop, but if that works looks good!

I don't even know what `AADClient.exe` is, so I'll let @suwatch  answer that.

**Comment by suwatch** [comment]
AADClient (not advertised much) is the client tool for AAD Graph.  Yes, do whatever the same as ARMClient.   

@snobu I am not familiar with scoop, but if you can share me some demo, I could include in ARMClient readme.

**Comment by snobu** [comment]
I'll add AADClient. Scoop is a choco-like package manager with two key differences - focuses on developer workloads and does not need admin privileges to install stuff (well, unless the package absolutely needs it - think Wireshark that needs WinPcap, a driver).

@suwatch This PR includes some changes to README, please review them. To test it out, install `scoop` from `https://scoop.sh`, then -

```
scoop install https://raw.githubusercontent.com/snobu/scoop/patch-1/bucket/armclient.json
```

After my PR gets merged to scoop's master all you need is -
```
scoop install armclient
```

**Comment by suwatch** [comment]
Thanks @snobu    Keep us informed on the PR integration.   Once done, i will include the information to ARMClient wiki.

**Comment by snobu** [comment]
PR into scoop is merged. You can merge this one and add to Wiki. Thanks!

**Comment by suwatch** [comment]
merged

**Pull request closed without merging**
